# Generated by Django 4.1.6 on 2023-04-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="nickname",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="user_id",
        ),
    ]
